site_name: MCAB Docs
site_description: MCAB Tutorial & Documentation
site_url: https://sslastochkin.github.io/mcab/

nav:
  - 'Main': README.md
  - 'Tutorial': 
    - 'First steps': 'tutorial/01_first_steps.md'
    - 'Data and Effects': 'tutorial/02_data_and_effects.md'
    - 'Variance Reduction': 'tutorial/03_variance_reduction.md'
    - 'Multiple Corrections': 'tutorial/04_multiple_corrections.md'
  - 'Api':
    - Overview: 'api/index.md'

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.instant
    - navigation.tracking
    - navigation.footer
    - toc.follow
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - content.tooltips
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
  font:
    text: Roboto
    code: Roboto Mono

repo_url: https://github.com/sslastochkin/mcab
repo_name: sslastochkin/mcab

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.mark
  - pymdownx.caret
  - pymdownx.tilde
  - pymdownx.keys
  - pymdownx.smartsymbols
  - attr_list
  - md_in_html
  - tables
  - footnotes
  - abbr
  - toc:
      permalink: true
      toc_depth: "1-6"
      
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css

plugins:
  - search:
      lang: en
  - minify:
      minify_html: true
  - mkdocs-jupyter:
      include_source: false
      ignore_h1_titles: true
      execute: false
  - mkdocstrings:
      handlers:
        python:
          paths: [src] # code path (src/mcab)
          options:
            docstring_style: google # google / numpy / sphinx
            show_source: true
            show_root_heading: true
            merge_init_into_class: true
