name: Documentation Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - '.github/workflows/docs_deploy.yml'
      - 'mkdocs_requirements.txt'

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r mkdocs_requirements.txt

      - name: Build the site
        run: mkdocs build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
